################################### Cluster ###################################
cluster.name: changoh_cluster

#################################### Node #####################################
node.name: changoh_home

################################### Memory ####################################
#bootstrap.memory_lock: true

############################## Network And HTTP ###############################
transport.tcp.port: 9333
http.port: 9222
http.host: 0.0.0.0
transport.host: 127.0.0.1

################################## CORS ##################################
http.cors.allow-origin: "/.*/"
http.cors.enabled: true

xpack.security.enabled: false
